// src/components/walltechhome/vue3/Portal.vue
<template>
  <div class="min-h-screen bg-white">
    <PortalHeader />
    <main>
      <PortalHero />
      <PortalFeatures />
      <PortalFeatureDetail />
      <PortalTechSpecs />
      <PortalCTA />
    </main>
    <PortalFooter />
  </div>
</template>

<script setup lang="ts">
import PortalHeader from './PortalHeader.vue'
import PortalFooter from './PortalFooter.vue'
import PortalHero from './PortalHero.vue'
import PortalFeatures from './PortalFeatures.vue'
import PortalFeatureDetail from './PortalFeatureDetail.vue'
import PortalTechSpecs from './PortalTechSpecs.vue'
import PortalCTA from './PortalCTA.vue'
import '../PortalStyles.css'

// Vue3 Portal组件，对应React版本的Portal.tsx
</script>

<style scoped>
/* Portal特定样式 */
</style>

// src/components/portalhome/Portal.tsx
import React from 'react';
import PortalHeader from './PortalHeader';
import PortalFooter from './PortalFooter';
import PortalHero from './PortalHero';
import PortalFeatures from './PortalFeatures';
import PortalSolutions from './PortalSolutions';
import PortalCTA from './PortalCTA';
import { UserProvider } from './UserContext';
import './PortalStyles.css';

const Portal: React.FC = () => {
  return (
    <UserProvider>
      <div className="min-h-screen bg-white">
        <PortalHeader />
        <main>
          <PortalHero />
          <PortalFeatures />
          <PortalSolutions />
          <PortalCTA />
        </main>
        <PortalFooter />
      </div>
    </UserProvider>
  );
};

export default Portal;
