// src/components/walltechhome/vue3/PortalHeader.vue
<template>
  <header class="bg-white/95 backdrop-blur-sm shadow-sm sticky top-0 z-50">
    <div class="container mx-auto px-4">
      <div class="flex items-center justify-between h-16">
        <!-- Logo区域 -->
        <div class="flex items-center space-x-4">
          <img 
            src="/assets/WX20250627-182147@2x.png" 
            alt="WallTech Logo" 
            class="h-8 w-auto"
          />
          <button 
            class="text-gray-600 hover:text-blue-600 transition-colors font-medium"
            @click="goHome"
          >
            回到首页
          </button>
        </div>

        <!-- 右侧按钮 -->
        <div class="flex items-center space-x-4">
          <button 
            class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition-colors"
            @click="handleLogin"
          >
            登录/注册
          </button>
        </div>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
// 事件处理函数
const goHome = () => {
  window.location.href = 'https://zh.etowertech.com/'
}

const handleLogin = () => {
  console.log('登录/注册')
  // 这里可以添加具体的登录逻辑
}
</script>

<style scoped>
/* PortalHeader特定样式 */
</style>

// src/components/portalhome/PortalHeader.tsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button } from '@arco-design/web-react';
import { IconMenu, IconClose } from '@arco-design/web-react/icon';

const PortalHeader: React.FC = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const navigate = useNavigate();

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  const navItems = [
    { label: '首页', href: '/portal' },
    { label: '控制塔', href: '/controltower' },
    { label: '业务介绍', href: '#services' },
    { label: '资讯中心', href: '#news' },
    { label: '关于我们', href: '#about' },
  ];

  return (
    <header className="bg-white shadow-sm sticky top-0 z-50">
      <div className="container mx-auto px-4 py-4 flex items-center justify-between">
        {/* Logo */}
        <Link to="/portal" className="flex items-center">
          <div className="flex items-center">
            <div className="bg-gradient-to-r from-blue-600 to-blue-400 text-white w-10 h-10 rounded-lg flex items-center justify-center mr-3 relative overflow-hidden shadow-lg">
              <span className="text-xl font-bold">Y</span>
              <div className="absolute bottom-0 right-0 w-3 h-3 bg-white rounded-tl-lg flex items-center justify-center">
                <span className="text-xs text-blue-600 font-bold">L</span>
              </div>
            </div>
            <div>
              <div className="text-lg font-bold text-gray-800 leading-tight tracking-wide">Your LOGO</div>
            </div>
          </div>
        </Link>

        {/* Desktop Navigation */}
        <nav className="hidden md:flex items-center space-x-8">
          {navItems.map((item, index) => (
            <Link 
              key={index}
              to={item.href} 
              className="text-gray-700 hover:text-blue-600 font-medium transition-colors"
            >
              {item.label}
            </Link>
          ))}
        </nav>

        {/* Login Button (Desktop) */}
        <div className="hidden md:block">
          <Button 
            type="primary" 
            className="bg-gradient-to-r from-blue-600 to-blue-400 border-0"
            onClick={() => navigate('/portal/auth')}
          >
            注册/登录
          </Button>
        </div>

        {/* Mobile Menu Button */}
        <div className="md:hidden">
          <button onClick={toggleMenu} className="text-gray-700">
            {isMenuOpen ? <IconClose /> : <IconMenu />}
          </button>
        </div>
      </div>

      {/* Mobile Navigation */}
      {isMenuOpen && (
        <div className="block md:hidden bg-white border-t border-gray-100 py-4">
          <div className="container mx-auto px-4 flex flex-col space-y-3">
            {navItems.map((item, index) => (
              <Link 
                key={index}
                to={item.href} 
                className="text-gray-700 hover:text-blue-600 py-2 font-medium"
                onClick={toggleMenu}
              >
                {item.label}
              </Link>
            ))}
            <Button 
              type="primary" 
              className="bg-gradient-to-r from-blue-600 to-blue-400 border-0 mt-2"
              onClick={() => navigate('/portal/auth')}
            >
              注册/登录
            </Button>
          </div>
        </div>
      )}
    </header>
  );
};

export default PortalHeader;
