// src/components/walltechhome/PortalTechSpecs.tsx
import React from 'react';
import { IconCloud, IconStar, IconUser } from '@arco-design/web-react/icon';

const PortalTechSpecs: React.FC = () => {
  return (
    <div className="py-20 bg-white">
      <div className="container mx-auto px-4">
        <div className="text-center mb-20">
          <h2 className="text-3xl font-bold text-gray-900 mb-12">
            技术优势与特性
          </h2>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-2xl p-8">
              <IconCloud className="text-5xl text-blue-600 mx-auto mb-4" />
              <h3 className="text-xl font-bold text-gray-900 mb-4">云原生架构</h3>
              <p className="text-gray-600">
                微服务架构设计，支持弹性扩容，高可用性保障，多环境部署灵活切换
              </p>
            </div>
            
            <div className="bg-gradient-to-br from-green-50 to-emerald-50 rounded-2xl p-8">
              <IconStar className="text-5xl text-green-600 mx-auto mb-4" />
              <h3 className="text-xl font-bold text-gray-900 mb-4">智能化程度高</h3>
              <p className="text-gray-600">
                深度学习算法，智能决策支持，自动化流程处理，持续优化提升
              </p>
            </div>
            
            <div className="bg-gradient-to-br from-purple-50 to-pink-50 rounded-2xl p-8">
              <IconUser className="text-5xl text-purple-600 mx-auto mb-4" />
              <h3 className="text-xl font-bold text-gray-900 mb-4">协作能力强</h3>
              <p className="text-gray-600">
                多角色协同工作，实时通信机制，流程透明可控，效率显著提升
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PortalTechSpecs;

// src/components/walltechhome/vue3/PortalTechSpecs.vue
<template>
  <section class="py-20 bg-gray-100">
    <div class="container mx-auto px-4">
      <div class="text-center mb-16">
        <h2 class="text-4xl font-bold text-gray-900 mb-4">技术特性</h2>
        <p class="text-xl text-gray-600">先进的技术架构，保障系统稳定高效</p>
      </div>
      
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div class="bg-white rounded-xl p-8 shadow-lg text-center">
          <i class="fas fa-cloud text-5xl text-blue-600 mb-4"></i>
          <h3 class="text-xl font-bold text-gray-900 mb-2">云原生架构</h3>
          <p class="text-gray-600">基于云原生技术构建，支持弹性扩展</p>
        </div>
        
        <div class="bg-white rounded-xl p-8 shadow-lg text-center">
          <i class="fas fa-brain text-5xl text-blue-600 mb-4"></i>
          <h3 class="text-xl font-bold text-gray-900 mb-2">智能化程度高</h3>
          <p class="text-gray-600">深度集成AI技术，自动化程度高</p>
        </div>
        
        <div class="bg-white rounded-xl p-8 shadow-lg text-center">
          <i class="fas fa-users text-5xl text-blue-600 mb-4"></i>
          <h3 class="text-xl font-bold text-gray-900 mb-2">协作能力强</h3>
          <p class="text-gray-600">支持多团队协作，实时信息同步</p>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
// 技术特性组件
</script>

<style scoped>
/* PortalTechSpecs特定样式 */
</style>
